import { readFile, writeFile, readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const directory = new URL("../docs/", import.meta.url);
const files = (await readdir(directory))
  .filter((name) => name.endsWith(".md") && name !== "README.md")
  .sort();
const documents = [];
for (const file of files) {
  const source = await readFile(new URL(file, directory), "utf8");
  const header = source.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!header) throw new Error(`${file}: missing front matter`);
  const fields = Object.fromEntries(
    header[1].split(/\r?\n/).map((line) => {
      const separator = line.indexOf(":");
      return [line.slice(0, separator), line.slice(separator + 1).trim()];
    }),
  );
  for (const key of ["title", "status", "type", "created", "updated"]) {
    if (!fields[key]) throw new Error(`${file}: missing ${key}`);
  }
  for (const key of ["created", "updated"]) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(fields[key])) throw new Error(`${file}: invalid ${key}`);
  }
  documents.push({ file, ...fields });
}
const english = documents.find((document) => document.file === "features.md");
const chinese = documents.find((document) => document.file === "features.zh-CN.md");
if (
  !english ||
  !chinese ||
  english.updated !== chinese.updated ||
  english.status !== chinese.status
) {
  throw new Error("Both feature guides must exist with matching updated dates and status.");
}
const content = `---
title: Desktop documentation
status: active
type: reference
created: 2026-09-24
updated: ${documents
  .map((document) => document.updated)
  .sort()
  .at(-1)}
---
# Desktop documentation / 开发文档

> Feature behavior and validation status / 功能行为与验证状态。

Update both language versions on every development change. See [AGENTS.md](../AGENTS.md).
每次开发同步更新中英文功能说明，包含限制和实际验证结果。

This index is generated by \`pnpm docs:sync\`; do not edit it by hand.
此索引由 \`pnpm docs:sync\` 生成，请勿手动修改。

<!-- BEGIN docs-index -->
| status | type | title |
| --- | --- | --- |
${documents.map((document) => `| ${document.status} | ${document.type} | [${document.title}](${document.file}) |`).join("\n")}
<!-- END docs-index -->
`;
const index = new URL("README.md", directory);
if (process.argv.includes("--check")) {
  if ((await readFile(index, "utf8")).replace(/\r\n/g, "\n") !== content) {
    throw new Error("Documentation index is stale. Run pnpm docs:sync.");
  }
  console.log("Documentation metadata and index are current.");
} else {
  await writeFile(index, content);
  console.log(`Updated ${fileURLToPath(index)}`);
}
